### ISSUE TITLE
Beef up the Keyboard View

### ISSUE THREAD

**Issue by aure** [AudioKit/Cookbook#1]
Add Polyphony button, increase/decrease number of octaves, up/down octave buttons to keyboard view

**Comment by emurray2** [comment]
In the AudioKit migration guide, each of the `OscillatorBank` classes have this description in the notes:

_This used a lot of AudioKit internals that were removed. You can use Synth for polyphonic sounds, and we hope to reintroduce polyphonic banks into AK5 soon._

Is there a way I could go about reintroducing the polyphonic banks so the polyphony toggle on the `KeyboardControl` fulfills its purpose?

I was thinking about looking back through AudioKit v4 and seeing if I could base the new implementation on that (of course without having to use the old AudioKit internals). Let me know if there's a better way. I'm open to suggestions.

**Comment by aure** [comment]
That would be a great achievement @emurray2. I'll help out however I can. The old code was ugly af and it should be basically a rewrite from scratch with inspiration from the old stuff.

**Comment by emurray2** [comment]
> That would be a great achievement @emurray2. I'll help out however I can. The old code was ugly af and it should be basically a rewrite from scratch with inspiration from the old stuff.

Awesome, I'll start working on it and see what I can do. This will give me some good practice with dynamic data structures in objective c++.

**Comment by emurray2** [comment]
@aure I just created a new branch on my local fork of SoundpipeAudioKit: https://github.com/emurray2/SoundpipeAudioKit/tree/v5-oscillator-banks so you can follow along.

**Comment by aure** [comment]
@emurray2 Following along, hard to keep up! ;)

**Comment by emurray2** [comment]
> @emurray2 Following along, hard to keep up! ;)

I know it's been a while, but I'm still working on this. I've moved the project over to here: https://github.com/emurray2/OscillatorBank.
