### ISSUE TITLE
Can't redirect output to bluetooth earphones

### ISSUE THREAD

**Issue by radiantdire** [AudioKit/Cookbook#10]
After installing this cookbook application on iphone x i am able to use the app however i am unable to hear the output, for ex. drums output from first mini app, using bluetooth earphones. I can hear sound from phone speakers. I had same issue for AudioKit playgrounds and bluetooth earphones but i could resolve it by just changing the microphone to system microphone on mac. However, i didn't find any way to change the input source of ios application. Is there any way for it to make it work?

**Comment by NickCulbertson** [comment]
I'm closing because it's 2 years old. If this is still an issue feel free to open it back up.
