### ISSUE TITLE
Missing package product 'CookbookCommon'

### ISSUE THREAD

**Issue by jrmgx** [AudioKit/Cookbook#100]
### macOS Version(s) Used to Build

macOS 12 Monterey

### Xcode Version(s)

Xcode 13.4.1

### Description

I wanted to try the Cookbook project on my machine but it won't compile.

../Cookbook.xcodeproj Missing package product 'CookbookCommon'

Showing Recent Messages
Couldn’t get revision ‘833aa2d007a3d82df232d788f4e0b006bdfa91f7^{commit}’:

### Crash Logs, Screenshots or Other Attachments (if applicable)

![Capture d’écran 2022-09-04 à 10 05 50](https://user-images.githubusercontent.com/42989/188303882-04c30047-db2a-4246-b164-87a01eb8122e.png)

**Comment by aure** [comment]
According to Github, this project is compiling fine as of the last commit: https://github.com/AudioKit/Cookbook/actions

**Comment by aure** [comment]
It looks like you have some extra weirdness at the end of the revision hash `^{commit}`

**Comment by aure** [comment]
Oddly enough I had that same `^{commit}` on a non-AudioKit repo I was checking out. I think this could be a bug in Xcode beta as I think was able to successfully build the project in Xcode 13.4.1. hth
