### ISSUE TITLE
Cookbook no longer runs xcode 14

### ISSUE THREAD

**Issue by rickhardy** [AudioKit/Cookbook#109]
### macOS Version(s) Used to Build

macOS 12 Monterey

### Xcode Version(s)

Xcode 14

### Description

Error is: 
/Cookbook/Cookbook/Cookbook.xcodeproj Missing package product 'CookbookCommon'

It expects that cookbookcommon is a package that should be added rather than integrated with the rest of Audiokit

**Comment by NickCulbertson** [comment]
Try File > Packages > Reset Package Caches.
