### ISSUE TITLE
Recommend moving that "work in progress" roland filter emulation to the "work in progress" folder. Can also replace that with a VCS3 filter instead.  

### ISSUE THREAD

**Issue by 01GOD** [AudioKit/Cookbook#114]
### Description

Nice progress team! First time I would say that Cookbook is getting into the innovative level of sound design. 
A little annoying to basically have to get up to speed on properly using SwiftUI, but that is doable. 
That roland filter emulation is incorrect (was incorrect in csound). That is supposed to be a lowpass filter that has a wide range and starts to "whistle" when CO is up near peak range when reso is all the way up. 
It seems some of the maths needs to be flipped in that emulation and maybe other adjustments also. 

### Proposed Solution

So, one option is to put that emulation into the "work in progress" folder of that app. And I can team up with somebody from AudioKit to have a look at that (I am alright with modifying the filter code, but I don't know the AK codebase enough to know where best to integrate it and how to easily and quickly test modifications and so on). 

### Describe Alternatives You've Considered

Another option is to simply to have a go at integrating this VCS3 filter emulation: https://github.com/VoggLyster/DiodeLadderFilter
That emulation author KINDLY added the appropriate licensing specifically to allow AudioKit to integrate that filter emulation. 
Although not COMPLETELY SURE that the VCS3 filter will sound identical to the roland, both are diode ladder filters.

**Comment by NickCulbertson** [comment]
#115 

Sure! I moved RolandTB303Filter to WIP because I noticed the audio got corrupted when turning the filter knob all the way down. I think the easy solution would be to change the min and max values of certain parameters of RolandTB303Filter in SoundpipeAudioKit. The issue for fixing RolandTB303Filter should be on the SoundpipAudioKit repo: https://github.com/AudioKit/SoundpipeAudioKit
