### ISSUE TITLE
CookBook package resolution does not work in Xcode 13

### ISSUE THREAD

**Issue by jalone87** [AudioKit/Cookbook#119]
### macOS Version(s) Used to Build

macOS 11 Big Sur

### Xcode Version(s)

Xcode 13.0

### Description

_I hope this ticket is not out of place, in such a case sorry, either way it can be closed promptly._

The project does not compile with xcode 13. It fail to build the package dependency graph.
I have been trying to fix it, since i think the main reason is that the only stable release of AudioKit for xcode 13 is 5.2.2, but the current CookBook requires 5.5.0 or such. 

I figure it's faster to install xcode on another machine than fix this issue, but for the future, **I would suggest git-tagging the commits or even better having releases, for each update of AudioKit**, or this information will be lost as soon as a new potentially unstable commit is pushed to master. 

Thank you for your work and time

**Comment by NickCulbertson** [comment]
I'm on Xcode 14 so I can't test this. Did you try File > Packages > Reset Package Caches?

**Comment by yfujiki** [comment]
It worked on my Xcode 14.1, but I had issues with package resolution too. The reason was that the package URL was described with HTTPS and even though theoretically, providing an access token should work, I went into an infinite loop of credential dialogs...

So, I changed the URLs to SSH, and voila!! success by giving a passphrase once.
Here is my `CookbookCommon/Package.swift`.

```
// swift-tools-version:5.5

import PackageDescription

let package = Package(
    name: "CookbookCommon",
    platforms: [.macOS(.v12), .iOS(.v15), .tvOS(.v15)],
    products: [.library(name: "CookbookCommon", targets: ["CookbookCommon"])],
    dependencies: [
        .package(url: "git@github.com:AudioKit/AudioKit", from: "5.5.4"),
        .package(url: "git@github.com:AudioKit/AudioKitUI", from: "0.3.4"),
        .package(url: "git@github.com:AudioKit/AudioKitEX", from: "5.5.0"),
        .package(url: "git@github.com:AudioKit/Controls", from: "1.0.0"),
        .package(url: "git@github.com:AudioKit/DunneAudioKit", from: "5.5.0"),
        .package(url: "git@github.com:AudioKit/Keyboard", from: "1.3.0"),
        .package(url: "git@github.com:AudioKit/SoundpipeAudioKit", from: "5.5.0"),
        .package(url: "git@github.com:AudioKit/SporthAudioKit.git", from: "5.5.0"),
        .package(url: "git@github.com:AudioKit/Tonic.git", from: "1.0.0"),
    ],
    targets: [
        .target(
            name: "CookbookCommon",
            dependencies: ["AudioKit", "AudioKitUI", "AudioKitEX", "Keyboard", "SoundpipeAudioKit", "SporthAudioKit", "DunneAudioKit", "Tonic", "Controls"],
            resources: [
                .copy("MIDI Files"),
                .copy("Samples"),
                .copy("Impulse Responses"),
            ]
        ),
        .testTarget(name: "CookbookCommonTests", dependencies: ["CookbookCommon"]),
    ]
)
```

**Comment by jalone87** [comment]
Yes, sadly no effect

**Comment by NickCulbertson** [comment]
I'm going to close this. Feel free to open it again if needed.
