### ISSUE TITLE
Does Audiokit provide any functionalites to play audio from NSData

### ISSUE THREAD

**Issue by NewajShovo** [AudioKit/Cookbook#130]
### Description

I have been using "The Amazing Audio Engine" and "AEAudioPlayable" for playing an audio stored in database as NSData. 
I want to replace the current framework to Audiokit but problem is that, I couldn't find any way to do it using audiokit.

### Proposed Solution

Is there any way currently here to implement this??

### Describe Alternatives You've Considered

Is there any way currently here to implement this??

**Comment by emurray2** [comment]
Yes, please see: [https://stackoverflow.com/questions/28048568/convert-avaudiopcmbuffer-to-nsdata-and-back](https://stackoverflow.com/questions/28048568/convert-avaudiopcmbuffer-to-nsdata-and-back). Then you can create an `AudioPlayer` instance and set its buffer using `myPlayer.buffer = AVAudioPCMBuffer(myData)`.

**Comment by emurray2** [comment]
Sure thing, here are the steps:

1. Create an instance of the audio player class
`var myPlayer = AudioPlayer()`

2. Convert your decided `NSData` from `Data` to `AVAudioPCMBuffer` using the code in the Stackoverflow link above

3. Set the buffer of your audio player to the chunk of data you want to play
`myPlayer.buffer = myData`

4. Play the player
`myPlayer.play()`
