### ISSUE TITLE
Cookbook does not build in Xcode 15 beta 2

### ISSUE THREAD

**Issue by misteu** [AudioKit/Cookbook#131]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 15 beta 2

### Description

The app does not build in Xcode 15 beta 2. I did not try beta 3 yet but I guess it will be the same there.

It seems to be because of one of the 3rd party libraries. The build error appears inside `WaveStack.cpp` which is inside of `CDunneAudioKit`

This might actually be more an issue of this 3rd party, but maybe it does make sense to exclude it for Xcode 15 builds of Cookbook as long as it's not working.

### Crash Logs, Screenshots or Other Attachments (if applicable)

<img width="991" alt="image" src="https://github.com/AudioKit/Cookbook/assets/35889530/8d21c600-24b6-4034-af71-2886790f920b">

**Comment by NickCulbertson** [comment]
The fixed version is on the assert-fixes branch (https://github.com/AudioKit/DunneAudioKit/tree/assert-fixes) but those have not been pulled into the DunneAudioKit Main branch yet. Those fixes should be rolled into the Main branch at some point soon. In the meantime you can replace the current DunneAudioKit package with the assert-fixes branch.

**Comment by aure** [comment]
Compiles for me. I addd back in Package.resolved so that we can pin versions, should help.
