### ISSUE TITLE
Mac Catalyst target build fails

### ISSUE THREAD

**Issue by ryfar** [AudioKit/Cookbook#136]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

When I attempt to build this project for Mac Catalyst on macOS Sonoma 14.0 with Xcode 15.0, build fails with the following failure:

.../AudioKitUI/Sources/AudioKitUI/Controls/ADSRView.swift:113:15 'prepareForInterfaceBuilder()' is unavailable in Mac Catalyst

Note that in this GitHub bug report form I had to select macOS 13 and Xcode 14 because it doesn't have options for macOS 14 or Xcode 15. But the issue is on macOS 14 and Xcode 15.

**Comment by NickCulbertson** [comment]
I'm seeing this crash. I guess it needs to be fixed on the AudioKitUI repo first.

**Comment by NickCulbertson** [comment]
This should be fixed in the latest version using AudioKitUI 0.3.6. Right click on the package > update package. Let me know how it goes!

**Comment by NickCulbertson** [comment]
If this is still an issue feel free to reopen it.
