### ISSUE TITLE
Build failed due to 'Keyboard' package

### ISSUE THREAD

**Issue by DanielFergusonMT** [AudioKit/Cookbook#150]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

Attempting to build the Cookbook throws back 'The package product 'Keyboard' requires minimum platform versions 16.0 for the iOS platform, but this target supports 15.0' despite target's being 17.2.

### Crash Logs, Screenshots or Other Attachments (if applicable)

<img width="707" alt="Screenshot 2024-01-30 at 14 10 58" src="https://github.com/AudioKit/Cookbook/assets/157504217/262cd8e4-ff0c-4fec-9dfd-ff5a38febd31">

**Comment by NickCulbertson** [comment]
Yeah, I'm seeing those too. I'll update the Tags to use the previous version.

**Comment by NickCulbertson** [comment]
The Cookbook was bringing in the latest versions of Controls and Keyboard which were just updated. Now those packages are set to exact Tags. You might have to File > Packages > Clear Package Caches.

**Comment by aure** [comment]
Yeah, sorry, I'm updating a bunch of dependencies for VisionOS. Will get it resolved shortly so we can get back on latest versions.

**Comment by DanielFergusonMT** [comment]
You guys are the best. Your hard work is an incredible contribution to the world - thank you so much! Just over a week ago I had no programming experience at all, and this project is helping me understand things that are way beyond me.
________________________________
