### ISSUE TITLE
Build issues with latest OS and XCode versions

### ISSUE THREAD

**Issue by domoritz** [AudioKit/Cookbook#16]
I am trying to build the app for iOS 14 on macOS 11 with XCode 12. 

```
Class 'WorkGroup' cannot conform to @objc protocol 'Repeatable' because the class is only visible via the Objective-C runtime
```

and

```
Failed to build module 'os' from its module interface; the compiler that produced it, 'Apple Swift version 5.3.1 (swiftlang-1200.2.40 clang-1200.0.32.7)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.16.109 clang-1200.0.22.20)'
```

Is there a particular setting I need to use to successfully build the app? 

Which versions do you recommend for building the app?

**Comment by megastep** [comment]
Are you using an older CocoaPod maybe?

**Comment by domoritz** [comment]
I just downloaded the cookbook and opened the project file in Xcode. It pulls the audio kit swift dependency from master.

**Comment by aure** [comment]
Looks like you have set things up correctly. I know a friend using MacOS11 has no problem. The errors you're reporting don't seem to have anything to do with AudioKit, so I wonder if the Sliders dependency is actually at fault.

**Comment by domoritz** [comment]
I do get an error in audiokit but I agree with you that the problem seems to be outside of audiokit. The issue could be my particular versions of the OS and XCode. I'll have to dig further myself. 

<img width="865" alt="Screen Shot 2020-10-16 at 20 40 34" src="https://user-images.githubusercontent.com/589034/96327594-d92ae700-0fef-11eb-8a87-9d97c8dc3283.png">

**Comment by aure** [comment]
Failed to build Accelerate! Yikes! I'm having a friend check it out on his macos11 machine, will report back.

**Comment by aure** [comment]
Yeah, it works for us on macOS11 as well. 🤷

**Comment by ryanfrancesconi** [comment]
accelerate is a built in library on macOS. Something is definitely weird about that error.

**Comment by domoritz** [comment]
Thanks for checking!
