### ISSUE TITLE
example of AudioPlayer fade in and fade out?

### ISSUE THREAD

**Issue by quantamrhino** [AudioKit/Cookbook#26]
I'm trying to use the automation events to automate fader gain, but I have a player with a seek bar and if I seek, it messes up the fades, as they are on AVAudioTime based on current time. 
Is there something I am missing?
Perhaps adding an example to the cookbook may help noobs like myself.
Thanks!

**Comment by NickCulbertson** [comment]
I'm closing because it's 2 years old. If this is still an issue feel free to open it back up.
