### ISSUE TITLE
Midi  and midi monitor example not working on macOS (Big Sur)

### ISSUE THREAD

**Issue by txbrown** [AudioKit/Cookbook#29]
Hi,

I have been trying Audiokit but I am struggling with making it work with my midi devices on macOS. I have seen this issue both on Cookbook as well following examples and applying them onto my "playground app" where I've been testing the features.

I can see this error being logged on any of the "test" apps I create on macOS and specifically only when instantiating the MIDI class:

```
2020-12-16 09:56:08.457326+0000 Cookbook[72432:2113908] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x6000032cc560> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2020-12-16 09:56:08.505460+0000 Cookbook[72432:2113908]  HALC_ShellDriverPlugIn::Open: opening the plug-in failed, Error: 2003329396 (what)
```

Please let me know if I can add more detail to clarify the issue here. I have looked before on the main Audiokit repo and it seems related to this issue - https://github.com/AudioKit/AudioKit/issues/2261

**Comment by aure** [comment]
I had no problems until I "upgraded" to Big Sur and now I also can't get AudioKit MIDI to work. I've been searching for information on what's going wrong, but I have put break points very deep in the code and I can't see any midi at all. Perhaps there's a problem opening inputs.

**Comment by aure** [comment]
I just pushed up an update to AudioKit's v5-develop branch that fixes the MIDI issues
