### ISSUE TITLE
AVAudioNodeCompletionHandler example

### ISSUE THREAD

**Issue by thejeff77** [AudioKit/Cookbook#30]
I'm being pretty dense and am trying to figure out how to use the completion handler. 

Would love an example. Thanks for any help or response!

**Comment by emurray2** [comment]
Just a heads up: `AudioPlayer` still has some bugs in the `main` branch of the AudioKit/AudioKit package. These will prevent this example from working. Until the next release, I've been using the `develop` branch instead.

**Comment by aure** [comment]
@emurray2 Is this closeable now?

**Comment by emurray2** [comment]
Yep, this should be in the Cookbook now
