### ISSUE TITLE
Is there a working "Getting Started" / HelloWorld example for AudioKit on MacOS?

### ISSUE THREAD

**Issue by chaimpeck** [AudioKit/Cookbook#31]
I would like to dive into AudioKit for MacOS, but have not been able to find a working example. Can anyone help with this? Thanks

**Comment by aure** [comment]
Its virtually identical to iOS. What's the problem?

**Comment by chaimpeck** [comment]
Except that some of the most basic examples do not work with AudioKit for MacOS projects.

I would like to see an example of a fully working simple project, and cannot seem to find one.

**Comment by aure** [comment]
Cookbook does work on the Mac too. I can walk through a macos example in a future office hours live stream.

**Comment by chaimpeck** [comment]
That would be helpful.
