### ISSUE TITLE
ParameterSlider not very responsive on macOS Big Sur

### ISSUE THREAD

**Issue by antiero** [AudioKit/Cookbook#32]
Testing Cookbook App built from Xcode 12.4 in macOS Big Sur 11.2, iMac (Retina 5K, 27-inch, 2019).

Not sure if this is just a SwiftUI bug or not...?

Most of the sliders (which use ParameterSlider) in the Cookbook app seem quite unresponsive in the latest macOS. The click hit zone seems small and it doesn't seem possible to make the slider jump to a position in the slider by clicking.

e.g. Open Drum Sequencer and try dragging the slider with the mouse/trackpad - it's hit-and-miss whether the slider moves!

To fix this in ParameterSlider.swift, I ended up replacing:

```
            ValueSlider(value: self.$parameter, in: self.range)
                .valueSliderStyle(HorizontalValueSliderStyle(
                    thumbSize: CGSize(width: 20, height: 20),
                    thumbInteractiveSize: CGSize(width: 44, height: 44)))
```

with the default SwiftUI slider:

`Slider(value: self.$parameter, in: self.range)`

https://user-images.githubusercontent.com/4693265/107946550-1779e800-6f89-11eb-866b-f28802c1ac33.mov

**Comment by aure** [comment]
This is definitely new. I don't think its just the sliders though. When the sliders are slow the whole UI seems lethargic at best.
