### ISSUE TITLE
SwiftUI lifecycle

### ISSUE THREAD

**Issue by transat** [AudioKit/Cookbook#33]
Any chance for instructions on how to set up the cookbook using the SwiftUI app lifecycle? Specifically, where should this bit from the AppDelegate go....?

```
#if os(iOS)
        do {
            Settings.bufferLength = .short
            try AVAudioSession.sharedInstance().setPreferredIOBufferDuration(Settings.bufferLength.duration)
            try AVAudioSession.sharedInstance().setCategory(.playAndRecord,
                                                            options: [.defaultToSpeaker, .mixWithOthers])
            try AVAudioSession.sharedInstance().setActive(true)
        } catch let err {
            print(err)
        }
        #endif
```

**Comment by aure** [comment]
You should be able to do this on your main ContentView() onAppear block.

**Comment by genedelisa** [comment]
import SwiftUI
import AVFoundation

@main
struct AVApp: App {
    
    #if os(macOS)
    @NSApplicationDelegateAdaptor(macOSNSAppDelegate.self) var appDelegate: NSAppDelegate
    #endif
    
    #if os(iOS)
    @UIApplicationDelegateAdaptor(iOSAppDelegate.self) var appDelegate
    #endif
    
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
    
}

#if os(iOS)
class iOSAppDelegate: UIResponder, UIApplicationDelegate {
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        
        do {
            try AVAudioSession.sharedInstance().setPreferredIOBufferDuration(1) // whatever
            try AVAudioSession.sharedInstance().setCategory(.playAndRecord,
                                                            options: [.defaultToSpeaker, .mixWithOthers])
            try AVAudioSession.sharedInstance().setActive(true)
        } catch let err {
            print(err)
        }
        return true
    }
}
#endif

#if os(macOS)
class macOSNSAppDelegate: NSObject, NSApplicationDelegate {
}
#endif

**Comment by aure** [comment]
Thanks for the pointers @genedelisa

**Comment by transat** [comment]
Another quick question: in general is it preferable to initialise a Conductor class here and share it everywhere in the app or to have individual Conductors for each view, as per the Cookbook examples?

**Comment by aure** [comment]
Really depends on your application. It used to be that we wholeheartedly recommended one Conductor app for technical reasons, but now I just think it keeps things simpler.
