### ISSUE TITLE
KeyboardWidget help

### ISSUE THREAD

**Issue by jgerontis** [AudioKit/Cookbook#34]
I'm working on building an app that has a keyboard in it. I want to start with Recipes/OscillatorView.swift, add it to my app, and then change much of it. That being said, OscillatorView.swift calls a "KeyboardWidget" and no matter what I include, I can't find where KeyboardWidget is defined or declared. Am I supposed to use KeyboardView instead?

**Comment by aure** [comment]
It was findable in a search. The file it was in was misnamed, so I at least fixed that.

**Comment by aure** [comment]
I guess the real question is whether KeyboardWidget should be moved to AudioKitUI. Right?

**Comment by jgerontis** [comment]
Thank you for your help. I'm still very new to Swift, SwiftUI, and AudioKit. Moving it to AudioKitUI makes sense, but I wouldn't take my word for it haha.

**Comment by aure** [comment]
KeyboardWidget might get renamed but it is in AudioKitUI now.
