### ISSUE TITLE
found 37 file(s) which are unhandled; explicitly declare them as resources or exclude from the target

### ISSUE THREAD

**Issue by transat** [AudioKit/Cookbook#35]
Whenever including AK5 in my projects, I get the following warning in XCode:

> found 37 file(s) which are unhandled; explicitly declare them as resources or exclude from the target

This happens with the Cookbook as well.

To quash the warnings though, should I be explicitly declaring these files or excluding them from the target?

**Comment by aure** [comment]
These are just README files that Xcode used to be able to ignore so we assumed this would just be a temporary annoyance and haven't done anything about it.

**Comment by eljeff** [comment]
I was able to supress one of these warnings in a test, but it  had to be done explicitly for each file and I think there has to be a better solution.

**Comment by transat** [comment]
Most are markdown files but there are actually quite a lot of C header files as well. e.g. 

> /Users/xxx/Library/Developer/Xcode/DerivedData/xyz-cgeebseytnxpiqdaodropmpxlrkn/SourcePackages/checkouts/AudioKit/Sources/CAudioKit/AudioKitCore/Common/AHDSHREnvelope.hpp

**Comment by aure** [comment]
I believe this is all resolved.
