### ISSUE TITLE
Feature Request: Playlist

### ISSUE THREAD

**Issue by transat** [AudioKit/Cookbook#36]
Would it be possible to have a basic "playlist" recipe?
Here's how it would work:

**- Given a [user-selected] folder on the filesystem, I would like to see list of all the audio files in that folder, along with a play button for each one.**

Currently the closest thing is the Drum Pad view, but in that recipe the audio file locations are hard-coded in the recipe's conductor rather than being dynamic and there is also the added complication of a grid with columns and rows (so not as beginner friendly for what should almost be the "hello world" of sample playback.)

**Comment by aure** [comment]
The work in this seems mostly on the operating system level as playing a file is pretty easy so I am not sure we need to provide code for that.

**Comment by transat** [comment]
Fair enough. I didn't find it so straightforward though. :-) Is there an AK guide? If so, it's not mentioned on the AK GitHub page. As it stands a new user has to find their way, unaided, to a specific page of the AK wiki docs to find out how to play an audio sample with AK5. And that page is not especially beginner friendly.
