### ISSUE TITLE
how do I change the Black background for the plots in Recorder

### ISSUE THREAD

**Issue by vittalk** [AudioKit/Cookbook#46]
Hi, 
I am playing with the cookbook. It is extremely useful. Thank you. 
I would like to change the black background for the plots in Recorder, Tuner etc. I tried a few things on the cookbook files, but I am unsuccessful. Please let me know how to change. I would like to parameterize the background color to any color, including clear. 

Thank you, 
-Vittal

**Comment by vittalk** [comment]
It looks like I would need to change the NodeOutputView in NodeOutputView.swift.  Please let me know if there is a better solution. thank you

**Comment by aure** [comment]
Sounds like you figured it out. AudioKitUI could be updated to allow for more flexibility, but that is not in the Cookbook scope.

**Comment by vittalk** [comment]
Actually, I haven’t.   So any help will be greatly appreciated.
Thanks
Vittal
________________________________
