### ISSUE TITLE
Recipe request: Read notes from a local MIDI file, loop over them and play the song on external output

### ISSUE THREAD

**Issue by ahilti** [AudioKit/Cookbook#47]
Basic Demo on how to **open a .mid file** and then **looping over all notes** for the given tracks displaying **key number, velocity, timestamp, duration, track and channel**. Basically having direct access to the notes themselves for further processing. Then **play the notes (file) on an output device** (preferably external, e.g. e-piano).
Right now, it seems very hard to find the relevant information to achieve this probably very simple task. Thanks!

**Comment by wtholliday** [comment]
Starting points might be `AppleSequencerTests` or `SequencerTrackTests` or `MIDIFile`. Feel free to submit a PR when it's done. Good luck.
