### ISSUE TITLE
PeakLimiter does not have an audible effect

### ISSUE THREAD

**Issue by eljeff** [AudioKit/Cookbook#48]
Adjusting pre-gain has no effect on the sound.

In my tests, you can set pre-gain before the app runs and it will have an effect, but you cannot adjust this parameter in realtime.

Other apple effects (PeakLimiter is an apple effect) work fine.

**Comment by aure** [comment]
This is not an issue in the Cookbook per se, but AudioKit itself, and there is already an issue there for this.
