### ISSUE TITLE
Pause/unpause audio recording

### ISSUE THREAD

**Issue by vittalk** [AudioKit/Cookbook#60]
HI Aure, 
How can I  Pause and Un-pause a recording ?   I've noticed that once I call recorder?.stop(), it completely stops the recording and I cant append to that file anymore even though I can toggle record and stop a few times.  Is this expected behavior
I'd like to have a pause functionality.  Any suggestions? 

thank you very much, 
-Vittal

**Comment by aure** [comment]
I guess I would consider keeping consecutive files and concatenating them when you're really done recording.
