### ISSUE TITLE
Feature Request: MultiSegmentPlayer Recipe

### ISSUE THREAD

**Issue by ShowtimeSoft** [AudioKit/Cookbook#70]
The new MultiSegmentPlayer seems cool; it would be nice with recipe on that one

**Comment by aure** [comment]
Agreed!

**Comment by Matt54** [comment]
Sorry I'm slacking! Will try to get around to this soon. I'll have to think of a simple "track with segments" view to represent this

**Comment by ShowtimeSoft** [comment]
I made very small demonstration "Section Player". It features 4 sections that can be played back in random order.
I did not use the MultiSegmentPlayer for this, because I couldn't grasp how it worked, but I'm sure you can use my player as an inspiration to show the segments.
You are welcome to use whatever from my source code, including the audio, which I did myself and therefore is free of any musical rights.

Compiled for macOS:
[SectionPlayer.zip](https://github.com/AudioKit/Cookbook/files/8186059/SectionPlayer.zip)

Source, Xcode 13.2.1
[SectionPlayer Source.zip](https://github.com/AudioKit/Cookbook/files/8186065/SectionPlayer.Source.zip)

**Comment by Matt54** [comment]
Closing this is with addition of #86
