### ISSUE TITLE
Feature Request: Waveform Display

### ISSUE THREAD

**Issue by ShowtimeSoft** [AudioKit/Cookbook#71]
I was trying to do a waveform display af an audio file, and tried the example in the Cookbook (Table Recipe).
While it does indeed display a waveform of an audio file, the method seems very slow to me.

While I was looking for a better and faster way, I found the Waveform and WavetableView in AudioKitUI, but no recipes on those. Now, wouldn't that be great to have such?

**Comment by Matt54** [comment]
This should be easy enough to add to AudioKitUI if it isn't already there. I have a lot of examples of this, but I'll check and see what Waveform/WavetableView look like first so that I don't reinvent the wheel...

**Comment by Matt54** [comment]
Closing this issue due to the addition of the "Audio Files View" to the Cookbook
