### ISSUE TITLE
Package graph doesn't resolve for latest release/Xcode 13.2

### ISSUE THREAD

**Issue by irskep** [AudioKit/Cookbook#72]
I'm not sure how to debug this because I'm not super familiar with SwiftPM, but I just cloned this project and wasn't able to build at all due to this error:
<img width="491" alt="Screen Shot 2021-12-19 at 9 07 00 AM" src="https://user-images.githubusercontent.com/40085/146683944-ff905f3f-b4eb-4f1e-8274-bbc856124000.png">

**Comment by wtholliday** [comment]
Might be an instance of that broken vision of Xcode Apple released.

**Comment by irskep** [comment]
Or it could be that the project specifies the AudioKitUI dependency as `main` instead of `5.2.0` 🤷 I'm checking now, but it's taking a while due to very slow internet.

**Comment by irskep** [comment]
That wasn't it, because AudioKitUI doesn't publish release versions. Giving up on this for now.

**Comment by wtholliday** [comment]
Resolves fine for me with 13.2.1.

**Comment by irskep** [comment]
Also worked for me. Thanks for your patience and quick response.
