### ISSUE TITLE
Example of how to combine two WAV files into one?

### ISSUE THREAD

**Issue by AttilaTheFun** [AudioKit/Cookbook#77]
I was wondering what the easiest way would be to load two (or more) WAV files and combine them into a single output WAV file. E.g. taking a vocal stem and combining that with an instrumental stem. I don't see a specific recipe for this, and to be honest it's a bit intimidating how many features and options there are. Could I get a couple of pointers here? If I manage to get it working, I could try to contribute the example back to the Cookbook!

**Comment by aure** [comment]
AudioKit doesn't have too much to do with audio file creation, besides recording. It would be a nice addition. It's not really a Cookbook issue though, since if it's not part of AudioKit it can't be in the Cookbook, so I will close this here.

**Comment by Matt54** [comment]
@AttilaTheFun Hey! This came across my email so I daydreamed about it while walking my dog. AudioKit may not currently have a solution, but here are some thoughts for putting one together:

If you find the function in AudioKit: loadAudioSignal(audioURL: URL) -> (signal: [Float], rate: Double, frameCount: Int)?

This will return for you an array of floating point values (signal) for a given audio file (as well as the sample rate and number of samples).

As far as combining lossless files go, we can think of it as simply adding the samples together. Assuming the sample rates of your two (or more) files are the same, then all you need to do is:
- loop for the longest sample count
- add all the existing samples from the audio files together at that index/frame
- hard clip / clamp to the min/max [probably just -1.0 / 1.0]

Then you will be left with a resulting floating point array with an associated sample rate (same from before) - I imagine that you could google your way to flipping that into an audio file from there 🙂

**Comment by Matt54** [comment]
@AttilaTheFun Things get more complicated if the sample rates are not the same. I can imagine then the solution would look like resampling any audio file that is not at whatever your desired output sample rate would be before doing the loop/arithmetic. 

Even still, it probably wouldn't be that bad. I think there are some Accelerate functions for performing this sort of resampling for you.

**Comment by AttilaTheFun** [comment]
Awesome, I'll see if I can get that working this weekend! 😊
