### ISSUE TITLE
Cookbook is broken due to missing MIDITrackViewModel

### ISSUE THREAD

**Issue by Matt54** [AudioKit/Cookbook#84]
Due to #82 

See https://github.com/AudioKit/AudioKitUI/pull/49

<img width="960" alt="Screen Shot 2022-03-07 at 9 30 37 PM" src="https://user-images.githubusercontent.com/15333030/157160836-5ebcf7a3-b6fe-4d33-a1b5-ba6803a030fc.png">

**Comment by aure** [comment]
This is addressed, amongst other things.
