### ISSUE TITLE
On latest commit of 'develop' branch the Cookbook/Cookbook/Recipes directory seems to be missing

### ISSUE THREAD

**Issue by landlessness** [AudioKit/Cookbook#90]
I watched @NickCulbertson's awesome YouTube video on making an instrument app with AudioKit.

After I cloned the Cookbook repo and switched to the 'develop' branch it seemed like the recipes folder went missing?

With commit 8e1a027c53 the file [InstrumentEXS.swift](https://github.com/AudioKit/Cookbook/blob/8e1a027c53bbbb61f5999df1f6f3854be133550f/Cookbook/Cookbook/Recipes/InstrumentEXS.swift) is in the Recipes directory.

However, with commit d6a74c975e the Recipes directory seems to have gone missing from [Cookbook/Cookbook](https://github.com/AudioKit/Cookbook/tree/d6a74c975e6879e319d91dc0662e1ee266bfe0a2/Cookbook/Cookbook).

My git skills are not strong. I apologize if this is just user error on my end.

**Comment by NickCulbertson** [comment]
The files were moved inside of the CookbookCommon package. Now the Cookbook is a Swift package like the other AudioKit modules. The path should be https://github.com/AudioKit/Cookbook/blob/develop/Cookbook/CookbookCommon/Sources/CookbookCommon/Recipes/InstrumentEXS.swift

Thanks for checking out the video and good luck experimenting!

**Comment by landlessness** [comment]
I see. Makes sense. Thanks for the quick response.  And thanks for sharing the great content.
