### ISSUE TITLE
Recorder error -50 on Mac OS  12.3.1

### ISSUE THREAD

**Issue by andrei4002** [AudioKit/Cookbook#95]
Hello, I'm trying to run the Recorder demo, building it on XCode 13.3.1 on Mac OS 12.3.1, Apple Silicon

pressing the record button in the demo doesn't seem to work, and i'm getting these errors spammed in the console indefinitely

```
[avae]            AVAEInternal.h:109   [AVAudioFile.mm:480:-[AVAudioFile writeFromBuffer:error:]: (ExtAudioFileWrite(_imp->_extAudioFile, buffer.frameLength, buffer.audioBufferList)): error -50
[general] NodeRecorder.swift:process(buffer:time:):177:Write failed: error -> The operation couldn’t be completed. (com.apple.coreaudio.avfaudio error -50.) (NodeRecorder.swift:process(buffer:time:):177)
```

Not sure if i'm doing anything wrong, I also tried creating a new project, adding AudioKit from SPM, setting it up with audio input in the App Sandbox settings,  and using the Recorder.swift file, but i'm getting the same errors

Other demos seem to work (like BaseTap for example)

I also tried it on an intel mac running xcode 13.0 / big sur, but i get into the same issues

**Comment by emurray2** [comment]
Fixed in AudioKit/AudioKit#2715

**Comment by lucarocchi** [comment]
got same issue on iOS , now resolved

**Comment by aure** [comment]
This should work now since the changes to AudioKit have been merged and tagged.
