### ISSUE TITLE
AudioKit Cookbook v.5 build fails (xcode 13.2.1)

### ISSUE THREAD

**Issue by Torrontes123** [AudioKit/Cookbook#96]
Description of the problem posted at https://stackoverflow.com/questions/72226789/audiokit-cookbook-v-5-build-fails-xcode-13-2-1

I'll be happy to go into more detail if necessary. Thanks.

**Comment by Torrontes123** [comment]
Thanks for the new commit. I am still facing the same issues, though.

**Comment by aure** [comment]
Clean the build folder?

**Comment by Torrontes123** [comment]
Hi. Thanks for the suggestion. I have done that repeatedly. 😊

Right now I'm trying recreating the entire project from scratch and see how
that goes. My current sticky point is "No such module CookbookCommon",
although I have added it as a local package and as a dependency.

Again, thanks for taking an interest in the problem.

**Comment by Torrontes123** [comment]
My attempt did not work. I am bumping against the same issues. I think
something is screwed up with my C++ headers in the iOS SDK. All the
problems have something to do with istream, ostream, sstream and the like.
I don't know what else to try. I have gotten rid of a whole bunch of error
messages like

No template named bitset
No template named num_get

by inserting

#include <locale>
#include <bitset>

in several of the STK headers, but other errors, such as

Invalid operands to binary expression ('std::ostream' (aka
'basic_ostream<char>') and 'const char [2]')

stubbornly remain. I am seriously considering going through all of the STK
package and commenting out all the statements printing to cerr, as well as
killing all related #include directives. I cannot think of any other course
of action.

Thanks

Gustavo (my real name)

**Comment by aure** [comment]
You can always check https://github.com/AudioKit/Cookbook/actions to see that the project is able to be built on a clean machine.

**Comment by Torrontes123** [comment]
I don't doubt that to be the case, but I don't see how that helps solve my
problem. Should I try reinstalling xcode? What do you think?

G.

**Comment by aure** [comment]
It helps you know that the problem is not here with us.  I am more than willing to help ith AudioKit problems, this is provably not that. Reinstalling your OS would definitely fix the problem and Xcode might fix your problem.

**Comment by Torrontes123** [comment]
Thank you. I appreciate your taking the time to reply.

G.

**Comment by Torrontes123** [comment]
I'm happy to report that reinstalling Xcode did the trick. Go figure. I
wonder if this happened because the previous installation was an upgrade
from 13.2, and this one was a totally fresh install. In any case, thank you
for taking an interest in the problem.

G.

**Comment by nmtitov** [comment]
Apologies for asking in wrong place...
Google points to this thread when searching "No template named 'num_get'"...

I had the same issue yesterday with Xcode 14.0 then I found this thread and reinstall Xcode 14.1. Now day after I have the same issue today with Xcode 14.1.
It came out of nowhere and now I can't even build the simplest program in the newly created project:

```
#include <iostream>

int main(int argc, const char * argv[]) {
    return 0;
}
```

^this fails to compile

If I remove `#include <iostream>` it works

<img width="256" alt="Screenshot 2022-11-27 at 20 13 19" src="https://user-images.githubusercontent.com/193307/204152488-a3d81219-f74c-4fa7-baa0-15a818f2c35d.png">

@Torrontes123 I wonder if you had any chance to figure out what went wrong?

**Comment by Torrontes123** [comment]
I really don't have a clue. I am still on Xcode 13, and in my case,
reinstallation cured the problem, but I have no insight on what the origin
of the problem was, it's a mystery to me. Sorry I'm not able to offer
better help
