### ISSUE TITLE
Cookbook Recorder Demo fails with "No file URL/settings to record to"

### ISSUE THREAD

**Issue by DrBilitski** [AudioKit/Cookbook#98]
To reproduce:
 open Recorder, tap record
Output console shows:
"NodeRecorder.swift:record():155:🛑 Error: No file URL/settings to record to (NodeRecorder.swift:record():155)"

Cookbook version is Latest version as of May 20, 2022 using AudioKit 5.4.2.

Sorry I don't know this project that well but it looks like the temp audio file created in `createAudioFile()` does not get updated to the variable `recordedFileURL`

**Comment by emurray2** [comment]
There were some recent changes to `NodeRecorder`. Try using the `main` branch of AudioKit, and let me know if that works. Thanks.

**Comment by DrBilitski** [comment]
The record demo works now using the main `branch`.

**Comment by emurray2** [comment]
> The record demo works now using the main `branch`.

That’s great to hear 🙂! I’ll close this for now, but feel free to re-open if it starts acting up again.
